### ISSUE TITLE
Add documentation with tips and tricks on how to configure Atom

### ISSUE THREAD

**Issue by lnnrtwttkhn** [lnnrtwttkhn/.atom#2]
The documentation could be based on [MkDocs](https://www.mkdocs.org/) which as an easy-to-use documentation software.

Deployment of the documentation could work via GitHub page using [this](https://github.com/mhausenblas/mkdocs-deploy-gh-pages) GitHub Action.

**Comment by lnnrtwttkhn** [comment]
hey @adswa, I tried to set-up thee GitHub Action for MkDocs deployment also in this repo but weirdly it does not seem to work and I am not sure what's missing.

Would you mind taking a brief look if you can spot the issue? Thank you very much!

**Comment by adswa** [comment]
I can't check your settings, but have you added a personal token? See: https://help.github.com/en/github/authenticating-to-github/creating-a-personal-access-token-for-the-command-line

**Comment by lnnrtwttkhn** [comment]
Thanks for your help @adswa!

Yes, I did it exactly like it said in the instructions.

The GitHub action also seems to work but the only thing that is showing up at https://lennartwittkuhn.com/.atom/ is the README file of the repo.

I thought it might be related to the custom domain of my user webpage https://lennartwittkuhn.com/ (hence I set the `CNAME` file in 
744ecce, d5e93a6 and ad9256a) but this didn't help.

**Comment by lnnrtwttkhn** [comment]
Ok, I think the main reason was a stupid mistake: Under the GitHub Pages I selected `master` and not `gh-pages` branch for deployment. However, when I changed it to `gh-pages`, I received this error / warning:

> The CNAME www.lennartwittkuhn.com/.atom is not properly formatted. See https://help.github.com/articles/troubleshooting-custom-domains/#github-repository-setup-errors for more information.

But the site shows up now! I will dig deeper into this warning but for now I am happy :)

**Comment by lnnrtwttkhn** [comment]
Just adding a few links for later reference:

- https://github.com/r-lib/pkgdown/issues/803
- https://help.github.com/en/github/working-with-github-pages/troubleshooting-jekyll-build-errors-for-github-pages-sites
- https://help.github.com/en/github/working-with-github-pages/managing-a-custom-domain-for-your-github-pages-site#configuring-a-records-with-your-dns-provider
- https://stackoverflow.com/questions/48919200/github-pages-only-showing-readme-file

**Comment by lnnrtwttkhn** [comment]
Ok, if I change the CNAME to `www.lennartwittkuhn.com` GitHub Pages also complains:

>  The CNAME www.lennartwittkuhn.com is already taken. Check out https://help.github.com/articles/troubleshooting-custom-domains#cname-errors for more information. 

Perhaps I don't even need the CNAME file? I'm gonna try that next.

**Comment by lnnrtwttkhn** [comment]
Cool, simply removing the `CNAME` file (see 79a83f5) solved the warnings!

And the documentation is live at: https://lennartwittkuhn.com/.atom/

Awesome!

Thanks again @adswa for your help and figuring out how to use the GitHub action for MkDocs deployment :pray:

Closing this issue.

**Comment by lnnrtwttkhn** [comment]
Just to summarize for future reference:
- Follow the instructions to deploy MkDocs documentation with [this](https://github.com/mhausenblas/mkdocs-deploy-gh-pages) GitHub Action
- Make sure to select the `gh-pages` branch as the source for GitHub Pages in the settings
- No need to fiddle with `CNAME` when using a custom domain on your user page (`<user_name>.github.io`)

**Comment by adswa** [comment]
wohoo! :tada:
